-- ROUND, TRUNC

-- SUM, AVG, COUNT, MAX, MIN

-- CASE
--     WHEN THEN
--     WHEN THEN
--     ELSE
-- END

-- 오라클
-- TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD')

-- MYSQL
-- DATE_FORMAT(INPUT_DATE, '%Y-%m-%d')

-- SELECT USER_ID, PRODUCT_ID
-- FROM ONLINE_SALE
-- GROUP BY USER_ID, PRODUCT_ID
-- HAVING COUNT(*) > 1 
-- ORDER BY USER_ID ASC, PRODUCT_ID DESC;